link:
	npm link babel-preset-es2015
	npm link babel-preset-react
	npm link babel-register
	npm link electron
	npm link react
	npm link react-dom
	npm link react-measure
	npm link sprintf-js

lint:
	eslint .
